file(GLOB invalid "${SOURCES}/examples/negative/*.tf")
list(APPEND invalid "${SOURCES}/examples/shape_error.tf")
foreach(source IN LISTS invalid)
  get_filename_component(name "${source}" NAME_WE)
  if(name STREQUAL "undeclared")
    set(required "undeclared identifier 'unknown'")
  elseif(name STREQUAL "duplicate")
    set(required "duplicate declaration 'A'")
  elseif(name STREQUAL "extent")
    set(required "tensor extent must be an integer")
  elseif(name STREQUAL "semicolon")
    set(required "expected ';'")
  elseif(name STREQUAL "token")
    set(required "invalid character")
  elseif(name STREQUAL "missing_return")
    set(required "final return statement")
  elseif(name STREQUAL "after_return")
    set(required "end of file after final return")
  elseif(name STREQUAL "shape_error")
    set(required "shape mismatch: tensor<4xf32> versus tensor<8xf32>")
  else()
    message(FATAL_ERROR "Negative fixture lacks expected diagnostic: ${source}")
  endif()
  execute_process(COMMAND "${CLI}" check "${source}" RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(status EQUAL 0 OR NOT err MATCHES "${required}" OR NOT err MATCHES ":[0-9]+:[0-9]+: error:" OR NOT err MATCHES "\\^")
    message(FATAL_ERROR "Expected nonzero exit and located diagnostic for ${source}: ${status} ${out} ${err}")
  endif()
endforeach()
